Relax pytest version constraint in tox minimal environment
Earlier, we required pytest<3.3.0 because we wanted it to work on Python
2.6 (which we no longer test with), and the catchlog plugin didn't have
a 'messages' attribute, so some tests failed like this:

    >       assert "BARMAN_BACKUP_DIR environment variable not set" in caplog.messages[0]
    E       AttributeError: 'CompatLogCaptureFixture' object has no attribute 'messages'

Since we are still testing with 2.7, we can use pytest 4.6.11 instead
(see https://docs.pytest.org/en/6.2.x/py27-py34-deprecation.html) with
its built-in catchlog and an updated pytest-timeout.