fix: barman-cloud-backup-delete invalid request
I'm backing up from cnpg barman-plugin to a NetApp StorageGrid S3 and
getting the following errors:
```
"Retention policy enforcement failed"
```

```
ERROR: Could not delete backup XXXXXXXXXXX: An error occurred (InvalidRequest) when calling the DeleteObjects operation: Missing required header for this request: Content-MD5\n",
```

According to the (Amazon S3 API
documentation)[https://docs.aws.amazon.com/AmazonS3/latest/API/API_DeleteObjects.html]
this is required
> General purpose bucket - The Content-MD5 request header is required for all Multi-Object Delete requests. Amazon S3 uses the header value to ensure that your request body has not been altered in transit.

But it looks like Amazon S3 and Boto don't use it while the Netapp does
follow the API Reference. This PR adds the header. I don't think adding
the header should be an issue for other implementations, if you think
otherwise I can add a flag to enable/disable it.