Fix PostgreSQL connection aliveness check
The previous code was raising an error when the PostgreSQL connection
was unexpectedly dropped:

    ERROR: Backup failed issuing stop backup command.
    DETAILS: 'NoneType' object has no attribute 'rollback'

Now the rollback is only issued when the connection is healty.

Regression introduced in 4b493022be79624da8deef95b88dd57b3ab5c12b

Closes: GH-239

Signed-off-by: Marco Nenciarini <marco.nenciarini@2ndquadrant.it>
Signed-off-by: Leonardo Cecchi <leonardo.cecchi@2ndquadrant.it>