Fix tox 'minimal' environment
1. Replace python2.6 with python2.7

2. Replace psycopg2==2.4.2 with psycopg2-binary (without any version
   constraint) because installing the former fails:

   Error: could not determine PostgreSQL version from '13.3'

   I don't know why 2.4.2, in particular, is considered "minimal", but
   without that constraint, the test succeeds. (Maybe the right thing to
   do would be to use the earliest version that can correctly parse 13.3
   as a version number, but I'm not sure what "minimal" is for, so…)