multiprocessing.Lock instead of threading.Lock
With the changes introduced in 3.18.0 to command_wrappers.py,
recovery fails with the error:
barman.copy_controller INFO: Copy failed
barman.cli ERROR: cannot pickle '_thread.lock' object
And the following messages in the log:
TypeError: cannot pickle '_thread.lock' object
when serializing dict item '_pipe_lock'
when serializing barman.command_wrappers.RsyncPgData state
when serializing barman.command_wrappers.RsyncPgData object
[..]

This commit removes the use of the threading.Lock() which cannot be
pickled by the ForkingPickler() class called from the function dump()
in the multiprocessing.reduction module which in turn is a pickle.Pickler()
subclass whose dump() function eventually calls the pickle.dump() function.

Instead multiprocessing.Lock() is used.

A Lock in the multiprocessing module seems to be a wrapper around a shared
semaphore (a SemLock object in multiprocessing/synchronize.py),
and since semaphores can be shared across process boundaries, no pickling
is needed.